language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - ./gradlew clean testDebugUnitTest

notifications:
  email: false
